/**
 * sets.js
 * Set data for One Piece and Pokémon TCG.
 * Pokémon image CDN: https://images.pokemontcg.io/{setId}/{number}_hires.png
 * One Piece image CDN: https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/{SET}/{CARD}_{LANG}.webp
 */

const SETS = {

  onePiece: [
    { id: 'OP01', name: 'OP01 - Romance Dawn' },
    { id: 'OP02', name: 'OP02 - Paramount War' },
    { id: 'OP03', name: 'OP03 - Pillars of Strength' },
    { id: 'OP04', name: 'OP04 - Kingdoms of Intrigue' },
    { id: 'OP05', name: 'OP05 - Awakening of the New Era' },
    { id: 'OP06', name: 'OP06 - Wings of the Captain' },
    { id: 'OP07', name: 'OP07 - 500 Years in the Future' },
    { id: 'OP08', name: 'OP08 - Two Legends' },
    { id: 'OP09', name: 'OP09 - The Four Emperors' },
    { id: 'OP10', name: 'OP10 - Royal Blood' },
    { id: 'OP11', name: 'OP11 - Memoir of Upheaval' },
    { id: 'OP12', name: 'OP12 - The Grandline Chronicles' },
    { id: 'OP13', name: 'OP13 - Hero of Justice' },
    { id: 'OP14', name: 'OP14 - 3D2Y' },
    { id: 'OP15', name: 'OP15 - Sealed Memories' },
    { id: 'ST01', name: 'ST01 - Straw Hat Crew' },
    { id: 'ST02', name: 'ST02 - Worst Generation' },
    { id: 'ST03', name: 'ST03 - The Seven Warlords' },
    { id: 'ST04', name: 'ST04 - Animal Kingdom Pirates' },
    { id: 'ST05', name: 'ST05 - Worst Generation 2' },
    { id: 'ST06', name: 'ST06 - Absolute Justice' },
    { id: 'ST07', name: 'ST07 - Big Mom Pirates' },
    { id: 'ST08', name: 'ST08 - Monkey D. Luffy' },
    { id: 'ST09', name: 'ST09 - Yamato' },
    { id: 'ST10', name: 'ST10 - UTA' },
    { id: 'ST11', name: 'ST11 - Uta' },
    { id: 'ST12', name: 'ST12 - Zoro & Sanji' },
    { id: 'ST13', name: 'ST13 - The Three Captains' },
    { id: 'ST14', name: 'ST14 - 3D2Y Luffy' },
    { id: 'ST15', name: 'ST15 - Red-Haired Pirates' },
    { id: 'ST16', name: 'ST16 - Marine' },
    { id: 'ST17', name: 'ST17 - Dark Forces' },
    { id: 'ST18', name: 'ST18 - World Government' },
    { id: 'ST19', name: 'ST19 - Final Chapter' },
  ],

  pokemon: [
    // Scarlet & Violet
    { id: 'sv9',     name: 'SV09 - Journey Together',       era: 'Scarlet & Violet' },
    { id: 'sv8pt5',  name: 'SV8.5 - Prismatic Evolutions',  era: 'Scarlet & Violet' },
    { id: 'sv8',     name: 'SV08 - Surging Sparks',         era: 'Scarlet & Violet' },
    { id: 'sv7',     name: 'SV07 - Stellar Crown',          era: 'Scarlet & Violet' },
    { id: 'sv6pt5',  name: 'SV6.5 - Shrouded Fable',        era: 'Scarlet & Violet' },
    { id: 'sv6',     name: 'SV06 - Twilight Masquerade',    era: 'Scarlet & Violet' },
    { id: 'sv5',     name: 'SV05 - Temporal Forces',        era: 'Scarlet & Violet' },
    { id: 'sv4pt5',  name: 'SV4.5 - Paldean Fates',         era: 'Scarlet & Violet' },
    { id: 'sv4',     name: 'SV04 - Paradox Rift',           era: 'Scarlet & Violet' },
    { id: 'sv3pt5',  name: 'SV3.5 - 151',                   era: 'Scarlet & Violet' },
    { id: 'sv3',     name: 'SV03 - Obsidian Flames',        era: 'Scarlet & Violet' },
    { id: 'sv2',     name: 'SV02 - Paldea Evolved',         era: 'Scarlet & Violet' },
    { id: 'sv1',     name: 'SV01 - Scarlet & Violet Base',  era: 'Scarlet & Violet' },
    // Sword & Shield
    { id: 'swsh12pt5', name: 'SWSH12.5 - Crown Zenith',     era: 'Sword & Shield' },
    { id: 'swsh12',  name: 'SWSH12 - Silver Tempest',       era: 'Sword & Shield' },
    { id: 'swsh11',  name: 'SWSH11 - Lost Origin',          era: 'Sword & Shield' },
    { id: 'swsh10',  name: 'SWSH10 - Astral Radiance',      era: 'Sword & Shield' },
    { id: 'swsh9',   name: 'SWSH09 - Brilliant Stars',      era: 'Sword & Shield' },
    { id: 'swsh8',   name: 'SWSH08 - Fusion Strike',        era: 'Sword & Shield' },
    { id: 'swsh7',   name: 'SWSH07 - Evolving Skies',       era: 'Sword & Shield' },
    { id: 'swsh6',   name: 'SWSH06 - Chilling Reign',       era: 'Sword & Shield' },
    { id: 'swsh5',   name: 'SWSH05 - Battle Styles',        era: 'Sword & Shield' },
    { id: 'swsh45',  name: 'SWSH4.5 - Shining Fates',       era: 'Sword & Shield' },
    { id: 'swsh4',   name: 'SWSH04 - Vivid Voltage',        era: 'Sword & Shield' },
    { id: 'swsh35',  name: "SWSH3.5 - Champion's Path",     era: 'Sword & Shield' },
    { id: 'swsh3',   name: 'SWSH03 - Darkness Ablaze',      era: 'Sword & Shield' },
    { id: 'swsh2',   name: 'SWSH02 - Rebel Clash',          era: 'Sword & Shield' },
    { id: 'swsh1',   name: 'SWSH01 - Sword & Shield Base',  era: 'Sword & Shield' },
    // Sun & Moon
    { id: 'sm12',    name: 'SM12 - Cosmic Eclipse',         era: 'Sun & Moon' },
    { id: 'sm115',   name: 'SM11.5 - Hidden Fates',         era: 'Sun & Moon' },
    { id: 'sm11',    name: 'SM11 - Unified Minds',          era: 'Sun & Moon' },
    { id: 'sm10',    name: 'SM10 - Unbroken Bonds',         era: 'Sun & Moon' },
    { id: 'sm9',     name: 'SM09 - Team Up',                era: 'Sun & Moon' },
    { id: 'sm8',     name: 'SM08 - Lost Thunder',           era: 'Sun & Moon' },
    { id: 'sm75',    name: 'SM7.5 - Dragon Majesty',        era: 'Sun & Moon' },
    { id: 'sm7',     name: 'SM07 - Celestial Storm',        era: 'Sun & Moon' },
    { id: 'sm6',     name: 'SM06 - Forbidden Light',        era: 'Sun & Moon' },
    { id: 'sm5',     name: 'SM05 - Ultra Prism',            era: 'Sun & Moon' },
    { id: 'sm4',     name: 'SM04 - Crimson Invasion',       era: 'Sun & Moon' },
    { id: 'sm35',    name: 'SM3.5 - Shining Legends',       era: 'Sun & Moon' },
    { id: 'sm3',     name: 'SM03 - Burning Shadows',        era: 'Sun & Moon' },
    { id: 'sm2',     name: 'SM02 - Guardians Rising',       era: 'Sun & Moon' },
    { id: 'sm1',     name: 'SM01 - Sun & Moon Base',        era: 'Sun & Moon' },
    // XY
    { id: 'xy12',    name: 'XY12 - Evolutions',             era: 'XY' },
    { id: 'xy11',    name: 'XY11 - Steam Siege',            era: 'XY' },
    { id: 'xy10',    name: 'XY10 - Fates Collide',          era: 'XY' },
    { id: 'xy9',     name: 'XY09 - BREAKpoint',             era: 'XY' },
    { id: 'xy8',     name: 'XY08 - BREAKthrough',           era: 'XY' },
    { id: 'xy7',     name: 'XY07 - Ancient Origins',        era: 'XY' },
    { id: 'xy6',     name: 'XY06 - Roaring Skies',          era: 'XY' },
    { id: 'xy5',     name: 'XY05 - Primal Clash',           era: 'XY' },
    { id: 'xy4',     name: 'XY04 - Phantom Forces',         era: 'XY' },
    { id: 'xy3',     name: 'XY03 - Furious Fists',          era: 'XY' },
    { id: 'xy2',     name: 'XY02 - Flashfire',              era: 'XY' },
    { id: 'xy1',     name: 'XY01 - XY Base',                era: 'XY' },
    // Black & White
    { id: 'bw11',    name: 'BW11 - Legendary Treasures',    era: 'Black & White' },
    { id: 'bw10',    name: 'BW10 - Plasma Blast',           era: 'Black & White' },
    { id: 'bw9',     name: 'BW09 - Plasma Freeze',          era: 'Black & White' },
    { id: 'bw8',     name: 'BW08 - Plasma Storm',           era: 'Black & White' },
    { id: 'bw7',     name: 'BW07 - Boundaries Crossed',     era: 'Black & White' },
    { id: 'bw6',     name: 'BW06 - Dragons Exalted',        era: 'Black & White' },
    { id: 'bw5',     name: 'BW05 - Dark Explorers',         era: 'Black & White' },
    { id: 'bw4',     name: 'BW04 - Next Destinies',         era: 'Black & White' },
    { id: 'bw3',     name: 'BW03 - Noble Victories',        era: 'Black & White' },
    { id: 'bw2',     name: 'BW02 - Emerging Powers',        era: 'Black & White' },
    { id: 'bw1',     name: 'BW01 - Black & White Base',     era: 'Black & White' },
    // HeartGold SoulSilver
    { id: 'col1',    name: 'HGSS - Call of Legends',        era: 'HeartGold SoulSilver' },
    { id: 'hgss4',   name: 'HGSS4 - Triumphant',            era: 'HeartGold SoulSilver' },
    { id: 'hgss3',   name: 'HGSS3 - Undaunted',             era: 'HeartGold SoulSilver' },
    { id: 'hgss2',   name: 'HGSS2 - Unleashed',             era: 'HeartGold SoulSilver' },
    { id: 'hgss1',   name: 'HGSS1 - HeartGold & SoulSilver',era: 'HeartGold SoulSilver' },
    // Diamond & Pearl / Platinum
    { id: 'pl4',     name: 'PL4 - Arceus',                  era: 'Diamond & Pearl' },
    { id: 'pl3',     name: 'PL3 - Supreme Victors',         era: 'Diamond & Pearl' },
    { id: 'pl2',     name: 'PL2 - Rising Rivals',           era: 'Diamond & Pearl' },
    { id: 'pl1',     name: 'PL1 - Platinum',                era: 'Diamond & Pearl' },
    { id: 'dp7',     name: 'DP7 - Stormfront',              era: 'Diamond & Pearl' },
    { id: 'dp6',     name: 'DP6 - Legends Awakened',        era: 'Diamond & Pearl' },
    { id: 'dp5',     name: 'DP5 - Majestic Dawn',           era: 'Diamond & Pearl' },
    { id: 'dp4',     name: 'DP4 - Great Encounters',        era: 'Diamond & Pearl' },
    { id: 'dp3',     name: 'DP3 - Secret Wonders',          era: 'Diamond & Pearl' },
    { id: 'dp2',     name: 'DP2 - Mysterious Treasures',    era: 'Diamond & Pearl' },
    { id: 'dp1',     name: 'DP1 - Diamond & Pearl Base',    era: 'Diamond & Pearl' },
    // EX era
    { id: 'ex16',    name: 'EX16 - Power Keepers',          era: 'EX Series' },
    { id: 'ex15',    name: 'EX15 - Dragon Frontiers',       era: 'EX Series' },
    { id: 'ex14',    name: 'EX14 - Crystal Guardians',      era: 'EX Series' },
    { id: 'ex13',    name: 'EX13 - Holon Phantoms',         era: 'EX Series' },
    { id: 'ex12',    name: 'EX12 - Legend Maker',           era: 'EX Series' },
    { id: 'ex11',    name: 'EX11 - Delta Species',          era: 'EX Series' },
    { id: 'ex10',    name: 'EX10 - Unseen Forces',          era: 'EX Series' },
    { id: 'ex9',     name: 'EX09 - Emerald',                era: 'EX Series' },
    { id: 'ex8',     name: 'EX08 - Deoxys',                 era: 'EX Series' },
    { id: 'ex7',     name: 'EX07 - Team Rocket Returns',    era: 'EX Series' },
    { id: 'ex6',     name: 'EX06 - FireRed & LeafGreen',    era: 'EX Series' },
    { id: 'ex5',     name: 'EX05 - Hidden Legends',         era: 'EX Series' },
    { id: 'ex4',     name: 'EX04 - Team Magma vs Team Aqua',era: 'EX Series' },
    { id: 'ex3',     name: 'EX03 - Dragon',                 era: 'EX Series' },
    { id: 'ex2',     name: 'EX02 - Sandstorm',              era: 'EX Series' },
    { id: 'ex1',     name: 'EX01 - Ruby & Sapphire',        era: 'EX Series' },
    // Neo / WotC / Classic
    { id: 'neo4',    name: 'Neo Destiny',                   era: 'Classic (WotC)' },
    { id: 'neo3',    name: 'Neo Revelation',                era: 'Classic (WotC)' },
    { id: 'neo2',    name: 'Neo Discovery',                 era: 'Classic (WotC)' },
    { id: 'neo1',    name: 'Neo Genesis',                   era: 'Classic (WotC)' },
    { id: 'gym2',    name: 'Gym Challenge',                 era: 'Classic (WotC)' },
    { id: 'gym1',    name: 'Gym Heroes',                    era: 'Classic (WotC)' },
    { id: 'base6',   name: 'Legendary Collection',         era: 'Classic (WotC)' },
    { id: 'base5',   name: 'Team Rocket',                   era: 'Classic (WotC)' },
    { id: 'base4',   name: 'Base Set 2',                    era: 'Classic (WotC)' },
    { id: 'fossil',  name: 'Fossil',                        era: 'Classic (WotC)' },
    { id: 'base2',   name: 'Jungle',                        era: 'Classic (WotC)' },
    { id: 'base1',   name: 'Base Set',                      era: 'Classic (WotC)' },
  ]
};
